name: Jukebox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildFw:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build firmware
      run: source bootstrap.sh && make -j
