name: Jukebox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildFw:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build firmware
      run: source bootstrap.sh && cmake -S . -B build/ -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake -DCMAKE_SYSTEM_NAME=Generic && cmake --build build
    - uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: build/Jukebox.elf

